import json
import logging
import os
import re
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from report import log_step


# ==========================================
# 1. CONFIGURATION
# ==========================================
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

INPUT_FILE      = os.path.join(BASE_DIR, 'data', 'output', 'reviews_translated.csv')
OUTPUT_FILE     = os.path.join(BASE_DIR, 'data', 'output', 'reviews_normalized.csv')
SLANG_DICT_FILE = os.path.join(BASE_DIR, 'data', 'input',  'manado_slang_dict.json')


# ==========================================
# 2. LOADER
# ==========================================
def load_slang_dict(filepath):
    """
    Loads the Manado slang dictionary from a JSON file.
    The file is generated by feeding top_words_raw.csv to Gemini AI (see Step 3).
    Returns a dict mapping slang/abbreviation → standard Bahasa Indonesia word.
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(
            f"Manado slang dictionary not found: {filepath}\n"
            f"Run Step 3 first to generate top_words_raw.csv, then follow the Gemini AI prompt."
        )
    with open(filepath, encoding='utf-8') as f:
        slang_dict = json.load(f)
    logging.info(f"Slang dictionary loaded: {len(slang_dict)} entries from {filepath}")
    return {k.lower(): v for k, v in slang_dict.items()}


# ==========================================
# 3. NORMALIZATION
# ==========================================
def build_pattern(slang_dict):
    """Compiles slang dictionary keys into a single regex pattern for efficient matching."""
    return re.compile(
        r'\b(' + '|'.join(map(re.escape, slang_dict.keys())) + r')\b',
        re.IGNORECASE
    )


def normalize_dialect(text, slang_dict, pattern):
    """
    Normalizes Manado dialect slang and common abbreviations to standard Bahasa Indonesia.
    Also replaces 'salah satu' with 'satu' to prevent the word 'salah' from being
    incorrectly detected as a negative sentiment token in the lexicon.
    Returns a tuple of (normalized_text, substitution_count).
    """
    if not isinstance(text, str):
        return text, 0

    text = text.lower()
    text = re.sub(r'\bsalah satu\b', 'satu', text)
    normalized, count = pattern.subn(
        lambda match: slang_dict[match.group(0).lower()], text
    )
    return normalized, count


def run_normalization(input_file, output_file):
    """
    Applies Manado dialect normalization to all review texts.
    Logs total substitutions made for quantitative reporting.
    """
    slang_dict = load_slang_dict(SLANG_DICT_FILE)
    pattern = build_pattern(slang_dict)

    logging.info(f"Loading dataset from: {input_file}")
    df = pd.read_csv(input_file)
    logging.info(f"Loaded {len(df)} rows.")

    total_substitutions = 0
    rows_affected = 0
    normalized_texts = []

    for text in df['review_text']:
        result, count = normalize_dialect(text, slang_dict, pattern)
        normalized_texts.append(result)
        if count > 0:
            total_substitutions += count
            rows_affected += 1

    df['review_text'] = normalized_texts

    affected_pct = rows_affected / len(df) * 100
    logging.info(f"Normalization complete. {total_substitutions:,} substitutions made across {rows_affected} rows ({affected_pct:.1f}% of corpus).")
    log_step('Step 4 - Dialect Normalization', f"{total_substitutions:,} substitutions across {rows_affected} rows ({affected_pct:.1f}% of corpus)")

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    df.to_csv(output_file, index=False)
    logging.info(f"Output saved to: {output_file}")


# ==========================================
# 3. ENTRY POINT
# ==========================================
if __name__ == '__main__':
    os.makedirs(os.path.join(BASE_DIR, 'data', 'output'), exist_ok=True)

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S',
        handlers=[
            logging.FileHandler(os.path.join(BASE_DIR, 'data', 'output', 'step4_dialect_normalization.log'), encoding='utf-8'),
            logging.StreamHandler(sys.stdout)
        ]
    )

    run_normalization(INPUT_FILE, OUTPUT_FILE)
